### PR TITLE
reduce noaa/aggs challenge runtime

### PR DESCRIPTION
**Pull request by salvatore-campagna**
This PR includes two changes:
1. Remove `target-interval`: targeting the reduction of the total performance test runtime
2. Execute terms queries on a subset of the date range: targeting the reduction of the runtime for the top two (by runtime) aggregations using the "map" hint

### CODE REVIEW

**Review by dliappis — APPROVED** [review]
LGTM

**Review by nik9000 — APPROVED** [review]
I don't really know what this does but I'm happy not to have those fiddly targets. If you like it I'm happy!

**Comment by salvatore-campagna** [comment]
After applying the additional changes I can see the test using the default car completing in 1 hour and 5 minutes.

**Review by nik9000 — APPROVED** [review]

**Comment by salvatore-campagna** [comment]
I will make another PR to include operations part of the `aggs` challenge part of the `default` challenge. Inclusion will take place according to a new command line parameter.

**Comment by dliappis** [comment]
> I will make another PR to include operations part of the `aggs` challenge part of the `default` challenge. Inclusion will take place according to a new command line parameter.

You mean you will address the refactoring in a separate PR and merge this for now as is? FYI I would be ok with this approach.

**Pull request merged**
