### PR TITLE
Update the aggs challenge for both the noaa and nyc_taxis tracks

### PR DESCRIPTION
**Pull request by salvatore-campagna**
Here we are doing the following:
* create an `aggs` challenge under the `nyc_taxis` which includes the following aggregations: `composite`, `sampler`, `percentiles`, `derivative` and `muti-terms`
* merge the `date-histogram` existing challenge under the new `nyc_taxis/aggs` challenge: as a result of this all `date-histogram` aggregations will be merged into the new `aggs` challenge
* merge the `top-metrics` existing challenge under the new `noaa/aggs` challenge: as a result of this all `top-metrics` and `top-hits` aggregations will be merged into the new `aggs` challenge
* include `rate` aggregations under the `nyc_taxis/aggs` challenge
* remove all `target-throughput` and `target-interval` parameters

After testing the new `aggs` challenge in the old nightly the number of iterations will be updated with an additional commit and later the challenge will be ready to be included to nightly benchmarks.

### CODE REVIEW

**Comment by salvatore-campagna** [comment]
After the changes above `noaa/aggs` takes 5337 seconds to complete which is about  1 hour and 28 mins instead of 1 hour and 5 minutes it took before. This increase in time is due to the additional operations included in the challenge.

**Review by dliappis — APPROVED** [review]
Thank you for iterating, improving and simplifying (merging existing challenges) the two tracks!

LGTM

**Comment by salvatore-campagna** [comment]
After testing both `noaa` and `nyc_taxis` I see the following runtime for the two `aggs` challenges:
* `nyc_taxis/aggs`: 6035 seconds (about 1 hour and 40 minutes) - still to be added to nightly
* `noaa/aggs`: 5407 seconds (about 1 hour and 30 minutes) - this is already part of nightly but has been extended

@dliappis are we fine with these timings?

**Comment by salvatore-campagna** [comment]
Extended by about 20 minutes. So we would go to about 13 hours and 20 minutes.

**Pull request merged**
