### PR TITLE
Iterate on date_histogram metrics

### PR DESCRIPTION
**Pull request by nik9000**
Iterates a bit on the date_histogram metrics, filtering "bad" data and increasing the throughput targets accordingly.

### CODE REVIEW

**Comment by nik9000** [comment]
I spent a *lot* of time hunting stuff down in https://github.com/elastic/elasticsearch/pull/57304 with this one. Ultimately I figured out that my proposal couldn't inline a method that had become bimorphic so I had to arm-wrestle it into being monomorphic again. Performance back.

**Comment by ebadyano** [comment]
@nik9000 Thank you for the PR, I'm running it on our env to see if service times/latency make sense. One concern I have, if we eventually want to add this to our nightlies, we may need to modify date_histogram challenge somehow, since it's taking more than 2.5 hours to run..

**Comment by nik9000** [comment]
>  since it's taking more than 2.5 hours to run..

Yeah. I'm not sure what to do about that. It really takes a long time to run across all that data. But it is important for the benchmark to do a wide range of dates. I wonder if maybe we would try to limit to some area in the city or something.

**Comment by ebadyano** [comment]
```
    ____        ____
   / __ \____ _/ / /_  __
  / /_/ / __ `/ / / / / /
 / _, _/ /_/ / / / /_/ /
/_/ |_|\__,_/_/_/\__, /
                /____/

[INFO] Preparing for race ...
[INFO] Racing on track [nyc_taxis], challenge [date-histogram] and car ['defaults', 'g1gc'] with version [8.0.0-SNAPSHOT].

Running delete-index                                                           [100% done]
Running create-index                                                           [100% done]
Running check-cluster-health                                                   [100% done]
Running index                                                                  [100% done]
Running refresh-after-index                                                    [100% done]
Running date_histogram_calendar_interval                                       [100% done]
Running date_histogram_calendar_interval_with_tz                               [100% done]
Running date_histogram_fixed_interval                                          [100% done]
Running date_histogram_fixed_interval_with_tz                                  [100% done]
Running date_histogram_fixed_interval_with_metrics                             [100% done]
Running auto_date_histogram                                                    [100% done]
Running auto_date_histogram_with_tz                                            [100% done]
Running auto_date_histogram_with_metrics                                       [100% done]

------------------------------------------------------
    _______             __   _____
   / ____(_)___  ____ _/ /  / ___/_________  ________
  / /_  / / __ \/ __ `/ /   \__ \/ ___/ __ \/ ___/ _ \
 / __/ / / / / / /_/ / /   ___/ / /__/ /_/ / /  /  __/
/_/   /_/_/ /_/\__,_/_/   /____/\___/\____/_/   \___/
------------------------------------------------------

|                                                         Metric |                                       Task |       Value |   Unit |
|---------------------------------------------------------------:|-------------------------------------------:|------------:|-------:|
|                     Cumulative indexing time of primary shards |                                            |     233.922 |    min |
|             Min cumulative indexing time across primary shards |                                            |     233.922 |    min |
|          Median cumulative indexing time across primary shards |                                            |     233.922 |    min |
|             Max cumulative indexing time across primary shards |                                            |     233.922 |    min |
|            Cumulative indexing throttle time of primary shards |                                            |           0 |    min |
|    Min cumulative indexing throttle time across primary shards |                                            |           0 |    min |
| Median cumulative indexing throttle time across primary shards |                                            |           0 |    min |
|    Max cumulative indexing throttle time across primary shards |                                            |           0 |    min |
|                        Cumulative merge time of primary shards |                                            |     79.6349 |    min |
|                       Cumulative merge count of primary shards |                                            |         247 |        |
|                Min cumulative merge time across primary shards |                                            |     79.6349 |    min |
|             Median cumulative merge time across primary shards |                                            |     79.6349 |    min |
|                Max cumulative merge time across primary shards |                                            |     79.6349 |    min |
|               Cumulative merge throttle time of primary shards |                                            |     20.8857 |    min |
|       Min cumulative merge throttle time across primary shards |                                            |     20.8857 |    min |
|    Median cumulative merge throttle time across primary shards |                                            |     20.8857 |    min |
|       Max cumulative merge throttle time across primary shards |                                            |     20.8857 |    min |
|                      Cumulative refresh time of primary shards |                                            |     1.40175 |    min |
|                     Cumulative refresh count of primary shards |                                            |         111 |        |
|              Min cumulative refresh time across primary shards |                                            |     1.40175 |    min |
|           Median cumulative refresh time across primary shards |                                            |     1.40175 |    min |
|              Max cumulative refresh time across primary shards |                                            |     1.40175 |    min |
|                        Cumulative flush time of primary shards |                                            |     2.97842 |    min |
|                       Cumulative flush count of primary shards |                                            |          32 |        |
|                Min cumulative flush time across primary shards |                                            |     2.97842 |    min |
|             Median cumulative flush time across primary shards |                                            |     2.97842 |    min |
|                Max cumulative flush time across primary shards |                                            |     2.97842 |    min |
|                                        Total Young Gen GC time |                                            |     138.631 |      s |
|                                       Total Young Gen GC count |                                            |       17137 |        |
|                                          Total Old Gen GC time |                                            |           0 |      s |
|                                         Total Old Gen GC count |                                            |           0 |        |
|                                                     Store size |                                            |     24.7512 |     GB |
|                                                  Translog size |                                            | 5.12227e-08 |     GB |
|                                         Heap used for segments |                                            |    0.185493 |     MB |
|                                       Heap used for doc values |                                            |   0.0343857 |     MB |
|                                            Heap used for terms |                                            |   0.0357819 |     MB |
|                                            Heap used for norms |                                            |           0 |     MB |
|                                           Heap used for points |                                            |           0 |     MB |
|                                    Heap used for stored fields |                                            |    0.115326 |     MB |
|                                                  Segment count |                                            |          28 |        |
|                                                 Min Throughput |                                      index |     72966.9 | docs/s |
|                                              Median Throughput |                                      index |     77837.7 | docs/s |
|                                                 Max Throughput |                                      index |     87699.2 | docs/s |
|                                        50th percentile latency |                                      index |     923.411 |     ms |
|                                        90th percentile latency |                                      index |     1641.51 |     ms |
|                                        99th percentile latency |                                      index |     3728.75 |     ms |
|                                      99.9th percentile latency |                                      index |     10200.9 |     ms |
|                                     99.99th percentile latency |                                      index |     11737.3 |     ms |
|                                       100th percentile latency |                                      index |       11838 |     ms |
|                                   50th percentile service time |                                      index |     923.474 |     ms |
|                                   90th percentile service time |                                      index |     1640.79 |     ms |
|                                   99th percentile service time |                                      index |     3726.81 |     ms |
|                                 99.9th percentile service time |                                      index |     10200.9 |     ms |
|                                99.99th percentile service time |                                      index |     11737.3 |     ms |
|                                  100th percentile service time |                                      index |       11838 |     ms |
|                                                     error rate |                                      index |           0 |      % |
|                                                 Min Throughput |           date_histogram_calendar_interval |         0.1 |  ops/s |
|                                              Median Throughput |           date_histogram_calendar_interval |         0.1 |  ops/s |
|                                                 Max Throughput |           date_histogram_calendar_interval |         0.1 |  ops/s |
|                                        50th percentile latency |           date_histogram_calendar_interval |     5975.31 |     ms |
|                                        90th percentile latency |           date_histogram_calendar_interval |     6019.79 |     ms |
|                                       100th percentile latency |           date_histogram_calendar_interval |     6067.29 |     ms |
|                                   50th percentile service time |           date_histogram_calendar_interval |     5970.69 |     ms |
|                                   90th percentile service time |           date_histogram_calendar_interval |     6014.36 |     ms |
|                                  100th percentile service time |           date_histogram_calendar_interval |     6060.86 |     ms |
|                                                     error rate |           date_histogram_calendar_interval |           0 |      % |
|                                                 Min Throughput |   date_histogram_calendar_interval_with_tz |        0.08 |  ops/s |
|                                              Median Throughput |   date_histogram_calendar_interval_with_tz |        0.08 |  ops/s |
|                                                 Max Throughput |   date_histogram_calendar_interval_with_tz |        0.08 |  ops/s |
|                                        50th percentile latency |   date_histogram_calendar_interval_with_tz |     8689.05 |     ms |
|                                        90th percentile latency |   date_histogram_calendar_interval_with_tz |     8824.42 |     ms |
|                                       100th percentile latency |   date_histogram_calendar_interval_with_tz |     9010.76 |     ms |
|                                   50th percentile service time |   date_histogram_calendar_interval_with_tz |     8685.12 |     ms |
|                                   90th percentile service time |   date_histogram_calendar_interval_with_tz |      8818.4 |     ms |
|                                  100th percentile service time |   date_histogram_calendar_interval_with_tz |     9005.29 |     ms |
|                                                     error rate |   date_histogram_calendar_interval_with_tz |           0 |      % |
|                                                 Min Throughput |              date_histogram_fixed_interval |         0.1 |  ops/s |
|                                              Median Throughput |              date_histogram_fixed_interval |         0.1 |  ops/s |
|                                                 Max Throughput |              date_histogram_fixed_interval |         0.1 |  ops/s |
|                                        50th percentile latency |              date_histogram_fixed_interval |     6096.91 |     ms |
|                                        90th percentile latency |              date_histogram_fixed_interval |     6196.04 |     ms |
|                                       100th percentile latency |              date_histogram_fixed_interval |     6266.23 |     ms |
|                                   50th percentile service time |              date_histogram_fixed_interval |      6091.2 |     ms |
|                                   90th percentile service time |              date_histogram_fixed_interval |     6190.74 |     ms |
|                                  100th percentile service time |              date_histogram_fixed_interval |     6260.55 |     ms |
|                                                     error rate |              date_histogram_fixed_interval |           0 |      % |
|                                                 Min Throughput |      date_histogram_fixed_interval_with_tz |        0.08 |  ops/s |
|                                              Median Throughput |      date_histogram_fixed_interval_with_tz |        0.08 |  ops/s |
|                                                 Max Throughput |      date_histogram_fixed_interval_with_tz |        0.08 |  ops/s |
|                                        50th percentile latency |      date_histogram_fixed_interval_with_tz |     8508.91 |     ms |
|                                        90th percentile latency |      date_histogram_fixed_interval_with_tz |     8590.47 |     ms |
|                                       100th percentile latency |      date_histogram_fixed_interval_with_tz |     8652.02 |     ms |
|                                   50th percentile service time |      date_histogram_fixed_interval_with_tz |      8503.3 |     ms |
|                                   90th percentile service time |      date_histogram_fixed_interval_with_tz |      8584.9 |     ms |
|                                  100th percentile service time |      date_histogram_fixed_interval_with_tz |     8646.42 |     ms |
|                                                     error rate |      date_histogram_fixed_interval_with_tz |           0 |      % |
|                                                 Min Throughput | date_histogram_fixed_interval_with_metrics |        0.03 |  ops/s |
|                                              Median Throughput | date_histogram_fixed_interval_with_metrics |        0.03 |  ops/s |
|                                                 Max Throughput | date_histogram_fixed_interval_with_metrics |        0.03 |  ops/s |
|                                        50th percentile latency | date_histogram_fixed_interval_with_metrics |     24856.6 |     ms |
|                                        90th percentile latency | date_histogram_fixed_interval_with_metrics |     25035.8 |     ms |
|                                       100th percentile latency | date_histogram_fixed_interval_with_metrics |     25573.8 |     ms |
|                                   50th percentile service time | date_histogram_fixed_interval_with_metrics |     24844.1 |     ms |
|                                   90th percentile service time | date_histogram_fixed_interval_with_metrics |     25022.3 |     ms |
|                                  100th percentile service time | date_histogram_fixed_interval_with_metrics |     25560.8 |     ms |
|                                                     error rate | date_histogram_fixed_interval_with_metrics |           0 |      % |
|                                                 Min Throughput |                        auto_date_histogram |        0.08 |  ops/s |
|                                              Median Throughput |                        auto_date_histogram |        0.08 |  ops/s |
|                                                 Max Throughput |                        auto_date_histogram |        0.09 |  ops/s |
|                                        50th percentile latency |                        auto_date_histogram |        7488 |     ms |
|                                        90th percentile latency |                        auto_date_histogram |     7635.32 |     ms |
|                                       100th percentile latency |                        auto_date_histogram |     7794.42 |     ms |
|                                   50th percentile service time |                        auto_date_histogram |     7482.04 |     ms |
|                                   90th percentile service time |                        auto_date_histogram |      7629.1 |     ms |
|                                  100th percentile service time |                        auto_date_histogram |     7788.63 |     ms |
|                                                     error rate |                        auto_date_histogram |           0 |      % |
|                                                 Min Throughput |                auto_date_histogram_with_tz |        0.05 |  ops/s |
|                                              Median Throughput |                auto_date_histogram_with_tz |        0.05 |  ops/s |
|                                                 Max Throughput |                auto_date_histogram_with_tz |        0.05 |  ops/s |
|                                        50th percentile latency |                auto_date_histogram_with_tz |     9754.53 |     ms |
|                                        90th percentile latency |                auto_date_histogram_with_tz |     9851.87 |     ms |
|                                       100th percentile latency |                auto_date_histogram_with_tz |      9961.4 |     ms |
|                                   50th percentile service time |                auto_date_histogram_with_tz |     9742.77 |     ms |
|                                   90th percentile service time |                auto_date_histogram_with_tz |      9839.7 |     ms |
|                                  100th percentile service time |                auto_date_histogram_with_tz |     9949.72 |     ms |
|                                                     error rate |                auto_date_histogram_with_tz |           0 |      % |
|                                                 Min Throughput |           auto_date_histogram_with_metrics |        0.02 |  ops/s |
|                                              Median Throughput |           auto_date_histogram_with_metrics |        0.02 |  ops/s |
|                                                 Max Throughput |           auto_date_histogram_with_metrics |        0.02 |  ops/s |
|                                        50th percentile latency |           auto_date_histogram_with_metrics |     29346.4 |     ms |
|                                        90th percentile latency |           auto_date_histogram_with_metrics |     29471.4 |     ms |
|                                       100th percentile latency |           auto_date_histogram_with_metrics |     29585.8 |     ms |
|                                   50th percentile service time |           auto_date_histogram_with_metrics |     29328.8 |     ms |
|                                   90th percentile service time |           auto_date_histogram_with_metrics |     29452.1 |     ms |
|                                  100th percentile service time |           auto_date_histogram_with_metrics |     29567.9 |     ms |
|                                                     error rate |           auto_date_histogram_with_metrics |           0 |      % |


-----------------------------------
[INFO] SUCCESS (took 11965 seconds)
```

**Comment by ebadyano** [comment]
Maybe running it against only a part of the corpus might make sense and get to more reasonable running time..

**Pull request merged**
