### PR TITLE
Remove `index.mode` gate on `copy_to`

### PR DESCRIPTION
**Pull request by salvatore-campagna**
This PR will be used to test an implementation of Elasrticsearch that supports copy_to for text fields. We make the field stored to mimic the actual copy_to implementation which will later use a stored field.

### CODE REVIEW

**Comment by salvatore-campagna** [comment]
NOTE: the CI is faling with an error that is expected with Elasticsearch 8.15 (missing `copy_to` support for `text` fields in Synthetic Source. This PR, anyway, is tested against an Elasticsearch PR which works-around that issue.

**Comment by gareth-ellis** [comment]
OK, will this change then be in 8.16? If so we should wait for the feature to merged into elasticsearch main, then backport this to a new 8.16 branch

**Comment by salvatore-campagna** [comment]
> OK, will this change then be in 8.16? If so we should wait for the feature to merged into elasticsearch main, then backport this to a new 8.16 branch

This is using a workaround that I just need for testing purposes. The actual fix will not require setting `store: true`. So once `copy_to` is supported it will end-up in Elasticsearch main and I will update this PR so to remove `store:true`. In the meanwhile I will use it like it is now.

**Comment by salvatore-campagna** [comment]
In order to get the original behaviour including copy_to I will just revert the original PR, merge and backport it.

**Pull request closed without merging**
