### PR TITLE
Change default store_type to fs

### PR DESCRIPTION
**Pull request by ebadyano**
Closes https://github.com/elastic/rally-tracks/issues/79

### CODE REVIEW

**Comment by ebadyano** [comment]
@dliappis One concern I have is that Daniel very recently delivered a chance in https://github.com/elastic/rally-tracks/commit/f1e41437e1ef29b29f34a532699f82ff4346954a where he used `hybridfs` as a default and not `fs`; wonder if I'm missing something for #79. Also I ran nested with the default changes to `fs`, seems to work fine. Any ideas?

**Comment by dliappis** [comment]
> where he used `hybridfs` as a default and not `fs`

As per https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules-store.html#file-system:

> fs
> Default file system implementation. This will pick the best implementation depending on the operating environment, which is currently hybridfs on all supported systems but is subject to change.

So currently (as of ES 7.0, please do double check the versions in the docs) `fs` equals `hybridfs` so we are ok.

I'd be careful about backporting this PR though to older branches esp. since `fs` became available after 7.0.

**Comment by danielmitterdorfer** [comment]
> I'd be careful about backporting this PR though to older branches esp. since fs became available after 7.0.

@ebadyano, @dliappis I think it is safe to backport this all the way until `5` as `fs` is [available there as well](https://www.elastic.co/guide/en/elasticsearch/reference/5.0/index-modules-store.html#file-system)? However, he `store_type` track parameter is currently available in `7`, `7.2`, `7.1` and `7.0` and I think we should backport this PR at least to these branches as well.

**Comment by dliappis** [comment]
Thanks @danielmitterdorfer 👍 on backporting to `7`, `7.2`, `7.1` and `7.0`.

**Comment by ebadyano** [comment]
Backported to 7, 7.1, 7.0.  I don't see 7.2 branch under rally-tracks..

**Comment by danielmitterdorfer** [comment]
> I don't see 7.2 branch under rally-tracks..

You're right. Thanks for backporting it!

**Pull request merged**
