### PR TITLE
Add new parameter to vector tracks to set vector index type

### PR DESCRIPTION
**Pull request by benwtrent**
This adds a new parameter for our vector tracks. In Elasticsearch 8.12 (not yet released), we introduce a new vector index kind. It will be useful to be able to run rally tracks against it.

This change will only work with Elasticsearch 8.12+, so I don't know what version of the tracks it should reside in.

### CODE REVIEW

**Review by jimczi — APPROVED** [review]
LGTM

**Review by inqueue — APPROVED** [review]
Would you mind dropping a line in the track README.md for the new parameter? Otherwise, LGTM.

**Comment by benwtrent** [comment]
@inqueue 🤔 for some reason the openAI benchmarks are complaining about the change. ARG!

**Comment by benwtrent** [comment]
> API verification failed with <class 'elasticsearch.AuthenticationException'>
 
Arg, CI doesn't like me at all :( @inqueue

**Comment by inqueue** [comment]
> > API verification failed with <class 'elasticsearch.AuthenticationException'>
> >  
> > Arg, CI doesn't like me at all :( @inqueue

Argh, I am very sorry. We can let this one go for now until we figure out what is going on with the test.

**Pull request merged**
