### PR TITLE
Enable `logsdb` index mode in security track

### PR DESCRIPTION
**Pull request by salvatore-campagna**
This PR changes the security track so that we can enable LogsDB
in index templates. Note that the failure store is only available in serverless
so we gate its usage excluding it in case the deployment is not serverless.

For LogsDB testing we rely on Kibana to install all other component/composable
templates. This is to make sure we need limited changes to the Rally track.

This needs to be backported to branch `8.15`.

### CODE REVIEW

**Comment by salvatore-campagna** [comment]
I am testing this using `esbench` both for stateful and serverless.

**Comment by salvatore-campagna** [comment]
@gareth-ellis @gbanasiak Serverless worked with the following params file, can we enable at lest the serverless nightly?

```
{
  "cloud.vendor": "aws",
  "cloud.region": "eu-west-1",
  "serverless.environment": "qa",
  "serverless.project_type": "security",
  "track.name": "elastic/security",
  "track.challenge": "security-indexing-querying",
  "on_error": "abort",
  "exclude.tasks": [
    "insert-pipelines",
    "insert-ilm",
    "delete-all-datastreams",
    "delete-all-composable-templates",
    "delete-all-component-templates",
    "create-all-component-templates",
    "create-all-composable-templates",
    "create-required-data-streams"
  ],
  "track.repository.url": "https://github.com/salvatore-campagna/rally-tracks.git",
  "track.revision": "b44bd172e37cf7e5ed23e8e9a5fe23e517c498be",
  "exclude.tasks": [
    "insert-ilm"
  ],
  "track.params": {
    "index_mode": "logsdb",
    "start_date": "2020-01-01",
    "end_date": "2020-01-02",
    "bulk_indexing_clients": 4,
    "data_generation_clients": 4,
    "raw_data_volume_per_day": "1MB",
    "max_generated_corpus_size": "10MB",
    "number_of_replicas": 1,
    "number_of_shards": 3,
    "wait_for_status": "green",
    "integration_ratios": {
      "logs-endpoint": {
        "corpora": {
          "endpoint-events-file": 0.2,
          "endpoint-events-library": 0.1,
          "endpoint-events-network": 0.2,
          "endpoint-events-process": 0.3,
          "endpoint-events-registry": 0.1,
          "endpoint-events-security": 0.1
        }
      }
    }
  },
  "client.options": {
      "default": {
          "timeout": 3600
      }
  }
}
```

**Comment by salvatore-campagna** [comment]
Stateful failed with the following error

```
esrally.exceptions.RallyError: Cannot run task [create-all-composable-templates]: Request returned an error. Error type: api, Description: invalid_index_template_exception ({'error': {'root_cause': [{'type': 'invalid_index_template_exception', 'reason': 'index_template [logs-endpoint.events.file] invalid, cause [index template [logs-endpoint.events.file] specifies component templates [logs-endpoint.events.file@package] that do not exist]'}], 'type': 'invalid_index_template_exception', 'reason': 'index_template [logs-endpoint.events.file] invalid, cause [index template [logs-endpoint.events.file] specifies component templates [logs-endpoint.events.file@package] that do not exist]'}, 'status': 400}), HTTP Status: 400
```

which is surprising because it means Kibana did not install the component template.

**Comment by salvatore-campagna** [comment]
After the latest commit 6bfdd20cd79d494c8ab96d9dfc4894dd0a6a2739 I tested both serverless and stateful and I see both complete successfully. For serverless I had to exclude yet another component template which is not installed by Kibana apparently.

**Comment by gbanasiak** [comment]
I don't understand why https://github.com/elastic/rally-tracks/pull/670/commits/6bfdd20cd79d494c8ab96d9dfc4894dd0a6a2739 was needed. The earlier custom component template exclusion is required due to https://github.com/elastic/rally/issues/1855, but `logs-endpoint.events.file@package` should be present.

Stateful cluster after Kibana installed latest `endpoint` package:
```
GET _cat/component_templates/*endpoint*?v&s=name
name                                         version alias_count mapping_count settings_count metadata_count included_in
.logs-endpoint.action.responses@package              0           14            3              3              [.logs-endpoint.action.responses]
.logs-endpoint.actions@package                       0           17            3              3              [.logs-endpoint.actions]
.logs-endpoint.diagnostic.collection@package         0           5             3              3              [.logs-endpoint.diagnostic.collection]
.logs-endpoint.heartbeat@package                     0           7             5              3              [.logs-endpoint.heartbeat]
logs-endpoint.alerts@package                         0           29            4              3              [logs-endpoint.alerts]
logs-endpoint.events.api@package                     0           12            3              3              [logs-endpoint.events.api]
logs-endpoint.events.file@package                    0           16            3              3              [logs-endpoint.events.file]
logs-endpoint.events.library@package                 0           16            3              3              [logs-endpoint.events.library]
logs-endpoint.events.network@package                 0           16            3              3              [logs-endpoint.events.network]
logs-endpoint.events.process@package                 0           17            3              3              [logs-endpoint.events.process]
logs-endpoint.events.registry@package                0           15            3              3              [logs-endpoint.events.registry]
logs-endpoint.events.security@package                0           13            3              3              [logs-endpoint.events.security]
metrics-endpoint.metadata@package                    0           9             5              3              [metrics-endpoint.metadata]
metrics-endpoint.metrics@package                     0           9             3              3              [metrics-endpoint.metrics]
metrics-endpoint.policy@package                      0           9             3              3              [metrics-endpoint.policy]
```

Serverless security project:
```
GET _cat/component_templates/*endpoint*?v&s=name
name                                         version alias_count mapping_count settings_count metadata_count included_in
.logs-endpoint.action.responses@package              0           14            2              3              [.logs-endpoint.action.responses]
.logs-endpoint.actions@package                       0           17            2              3              [.logs-endpoint.actions]
.logs-endpoint.diagnostic.collection@package         0           5             2              3              [.logs-endpoint.diagnostic.collection]
.logs-endpoint.heartbeat@package                     0           7             4              3              [.logs-endpoint.heartbeat]
logs-endpoint.alerts@package                         0           29            3              3              [logs-endpoint.alerts]
logs-endpoint.events.api@package                     0           12            2              3              [logs-endpoint.events.api]
logs-endpoint.events.file@package                    0           16            2              3              [logs-endpoint.events.file]
logs-endpoint.events.library@package                 0           16            2              3              [logs-endpoint.events.library]
logs-endpoint.events.network@package                 0           16            2              3              [logs-endpoint.events.network]
logs-endpoint.events.process@package                 0           17            2              3              [logs-endpoint.events.process]
logs-endpoint.events.registry@package                0           15            2              3              [logs-endpoint.events.registry]
logs-endpoint.events.security@package                0           13            2              3              [logs-endpoint.events.security]
metrics-endpoint.metadata@package                    0           9             4              3              [metrics-endpoint.metadata]
metrics-endpoint.metrics@package                     0           9             2              3              [metrics-endpoint.metrics]
metrics-endpoint.policy@package                      0           9             2              3              [metrics-endpoint.policy]
```

`logs-endpoint.events.file@package` is present in both.

**Comment by gbanasiak** [comment]
@salvatore-campagna Can we modify track README to include the information about `index_mode` and a note that `logsdb` is for internal testing only?

**Review by gbanasiak — APPROVED** [review]
Thank you for all the iterations. LGTM.

**Pull request merged**
