### PR TITLE
Re-enable `copy_to` into `elastic/security`

### PR DESCRIPTION
**Pull request by salvatore-campagna**
`copy_to` is used to copy from `kubernetes.event.message` to `message`.
Now it is supported in Elasticsearch 8.15 and we can benchmark the security
track including it. We also remove a parameter which was used to run a modified
workflow, which was using `kubernetes.event.message` instead of `message`.

This needs backporting to `8.15`

### CODE REVIEW

**Comment by salvatore-campagna** [comment]
@elastic/es-perf there is an error somewhere here which I am not able to debug since `esrally` is not working.
Maybe someone could help here. It is probably a typo, a missing parenthesis or something like that. Not having `esrally` working it is a bit difficult for me to spot.

**Comment by salvatore-campagna** [comment]
I get the following error in `esbench` which I wanted to debug in `esrally`. I don't know where this is coming from.

```
(.venv) Salvatores-MBP:elasticsearch-benchmarks salvatore.campagna$ esbench start --use-case=simple --params=elastic-security/params-logsdb-security-stateful-with-copy-to-contender.json
/Users/salvatore.campagna/workspace/elasticsearch-benchmarks/.venv/lib/python3.10/site-packages/paramiko/pkey.py:82: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "cipher": algorithms.TripleDES,
/Users/salvatore.campagna/workspace/elasticsearch-benchmarks/.venv/lib/python3.10/site-packages/paramiko/transport.py:253: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "class": algorithms.TripleDES,

    ______     __                    __
   / ____/____/ /_  ___  ____  _____/ /_
  / __/ / ___/ __ \/ _ \/ __ \/ ___/ __ \
 / /___(__  ) /_/ /  __/ / / / /__/ / / /
/_____/____/_.___/\___/_/ /_/\___/_/ /_/


*********************************************************************************************************************************************************
[WARNING] Your Slack member ID was auto-detected. More info: https://docs.elastic.dev/es-benchmarking/esbench/documentation/overview#slack-notifications.
*********************************************************************************************************************************************************

Add the following section to your ~/.esbench/esbench.toml file to get rid of the above warning:
[slack]
channel_id="U02K8FH239V"

Traceback (most recent call last):
  File "/Users/salvatore.campagna/workspace/elasticsearch-benchmarks/.venv/bin/esbench", line 8, in <module>
    sys.exit(main())
  File "/Users/salvatore.campagna/workspace/elasticsearch-benchmarks/.venv/lib/python3.10/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/salvatore.campagna/workspace/elasticsearch-benchmarks/.venv/lib/python3.10/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/salvatore.campagna/workspace/elasticsearch-benchmarks/.venv/lib/python3.10/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/salvatore.campagna/workspace/elasticsearch-benchmarks/.venv/lib/python3.10/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/salvatore.campagna/workspace/elasticsearch-benchmarks/.venv/lib/python3.10/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/salvatore.campagna/workspace/elasticsearch-benchmarks/esbench/esbench.py", line 268, in start
    runner.start(use_case=use_case, user_params=to_dict(params), config=cfg)
  File "/Users/salvatore.campagna/workspace/elasticsearch-benchmarks/esbench/utils/transforms.py", line 76, in to_dict
    return json.load(f)
  File "/Users/salvatore.campagna/.pyenv/versions/3.10.9/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/Users/salvatore.campagna/.pyenv/versions/3.10.9/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Users/salvatore.campagna/.pyenv/versions/3.10.9/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/salvatore.campagna/.pyenv/versions/3.10.9/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 36 column 1 (char 1099)```

**Comment by salvatore-campagna** [comment]
@gareth-ellis if this is green I would like to use it to enable `elastic/security` in nightlies. I will need to update the other PR in the `elasticsearch-benchmarks` repo to add the appropriate configs.

**Review by gareth-ellis — APPROVED** [review]

**Comment by salvatore-campagna** [comment]
`copy_to` is used to copy from `kubernetes.event.message` to `message`.
Now it is supported in Elasticsearch 8.15 and we can benchmark the security
track including it. We also remove a parameter which was used to run a modified
workflow, which was using `kubernetes.event.message` instead of `message`.

**Pull request merged**
