### PR TITLE
ESQL: Load 500 rows

### PR DESCRIPTION
**Pull request by nik9000**
This adds a test that *just* loads 500 rows with ESQL. Against an index with *thousands* of fields. Those thousands of fields are pretty expensive for ESQL to load, much more expensive than _search. Because ESQL doesn't have any "just load the _source" style optimizations.

### CODE REVIEW

**Comment by nik9000** [comment]
How do I fix the ` CI / rally-tracks-compat 3.8 (pull_request)` build?

**Review by craigtaverner — APPROVED** [review]
Nice to have some ESQL in TSDB track. Do we need a review by anyone in TSDB?

**Comment by craigtaverner** [comment]
> How do I fix the ` CI / rally-tracks-compat 3.8 (pull_request)` build?

The two `rally-tracks-compat` builds are the only ones that run the full track, and both fail with the same error:

```
Cannot run task [esql-fetch-500]: Request returned an error:

"fetching values from a text field [as.organization.name.text] is not supported because synthetic _source is enabled and we don't have a way to load the fields"
```

Is this a conflict between TSDB and ESQL? One needs synthetic source and the other can't handle it?

**Comment by nik9000** [comment]
https://github.com/elastic/elasticsearch/pull/102490 should fix these.

**Comment by nik9000** [comment]
elasticmachine, test this please

**Comment by nik9000** [comment]
> [elastic/elasticsearch#102490](https://github.com/elastic/elasticsearch/pull/102490) should fix these.

I've merged that so the tests should pass.

**Comment by nik9000** [comment]
@elasticmachine, update branch

**Comment by nik9000** [comment]
Looks like this is still failing, but the bug in ES is fixed. I'll bet it needs a snapshot or something.

**Comment by nik9000** [comment]
Neat! It closes as soon as I open it. Weird! I'll remake.

**Comment by pmpailis** [comment]
The issue with automatically closing should be resolved now - reopened :)

**Comment by nik9000** [comment]
> The issue with automatically closing should be resolved now - reopened :)

Thanks! I think I want to merge this now!

**Pull request closed without merging**
