### PR TITLE
Add benchmark for top_metrics fetching keyword

### PR DESCRIPTION
**Pull request by nik9000**
Tests for the speed cost of implementing
https://github.com/elastic/elasticsearch/pull/70579

### CODE REVIEW

**Review by danielmitterdorfer — APPROVED** [review]
Thanks! LGTM

**Comment by dliappis** [comment]
@nik9000 how far back should we backport this (specifically wondering about 7.x)?

**Comment by nik9000** [comment]
It won't work before about 7.13. Before that it's just errors. Might be
7.12. But doesn't need to go back that far because we aren't running in
nighties. Just 7.latest is cool

**Comment by dliappis** [comment]
> It won't work before about 7.13. Before that it's just errors. Might be 7.12. But doesn't need to go back that far because we aren't running in nighties. Just 7.latest is cool

We have a branch `7.12` which covers `7.12` (inclusive) and everything newer than that. We are good with that I guess?

**Comment by nik9000** [comment]
great!

**Comment by dliappis** [comment]
Cherry picked in 7.12 via fadc9a887b3a52681551171b00cf416e51e60ff9

**Pull request merged**
