### PR TITLE
Update synthetic source config

### PR DESCRIPTION
**Pull request by nik9000**
This flips `text` fields from having a sub-keyword field to `stored`
fields and it re-enables `ignore_above` on all `keyword` fields now that
synthetic source supports that.

### CODE REVIEW

**Comment by nik9000** [comment]
I'm using this to test the performance of https://github.com/elastic/elasticsearch/pull/89466 - once that's merged we can merge this.

**Review by DJRickyB — APPROVED** [review]
LGTM from a correctness standpoint

**Comment by nik9000** [comment]
It will change "what we're doing" in the nightlies for tsdb, but it'll change it to something a little more realistic.

**Comment by nik9000** [comment]
@DJRickyB What should I do about backporting this? It can only run on 8.5+.

**Pull request merged**
