### PR TITLE
Switch runtime_script_grok to _source

### PR DESCRIPTION
**Pull request by nik9000**
This switches the `runtime_script_grok` track to load from `_source` by
default and makes it possible to configure it to load from either
`_source`, a `wildcard` field, or a `keyword` field.

Loading values from `_source` is more realistic for the "saving space"
use case and we should see that in the index size. Loading from
`wildcard` would be more realistic in the "flexibility" use case so that
is useful to run locally, but for now it makes sense to run the "saving
space" use case in rally. Loading values from a `keyword` field is
useful mostly as a baseline to compare to the `wildcard` field. We
*think* `wildcard` is always better at flexibility and `_source` is
always better at saving space, but being able to test `keyword` will
validate our theories.

### CODE REVIEW

**Review by danielmitterdorfer — APPROVED** [review]
It took a while to review this as I tested each of the three possible configurations. The benchmarks themselves look fine and I only found one typo in the docs. LGTM (no need for another review around after fixing the typo and the merge conflict).

**Comment by nik9000** [comment]
I believe I've resolved the typo and merge conflict. I'll give the three options another roll through today to double check everything. @danielmitterdorfer, in the past y'all have merged merge my PRs and backported them. Would you like to do that still? I keep opening PRs over here so maybe I should learn to do it myself?

**Comment by danielmitterdorfer** [comment]
> In the past y'all have merged merge my PRs and backported them. Would you like to do that still? I keep opening PRs over here so maybe I should learn to do it myself?

It would be great if you could pick this up. Backports are done by cherry-picking the commit on the right branch (in your case it's only branch `7`). Contrary to the ES repo, we don't to backport PRs but rather push directly to the remote. In order to avoid any disruptions in the nightly benchmarks over the weekend we don't merge PRs on the last day of the week (i.e. on Fridays).

**Comment by nik9000** [comment]
Got it! I can do that.

**Comment by nik9000** [comment]
I've merged and backported! I'll try and remember to look at the nightlies in the morning.

**Pull request merged**
