### PR TITLE
Make ml-job do work so time measurements mean something

### PR DESCRIPTION
**Pull request by benwtrent**
This commit makes the nyc_taxis machine learning job more complex. 
The job for `append-ml` was too simple and end of bucket processing time was almost always under 1 ms. This increases partitions + detectors so that processing actually takes time.

### CODE REVIEW

**Comment by ebadyano** [comment]
@benwtrent I tried running it on low-mem env. It seems to be taking quite a long time, it's been on `wait-for-ml-lookback ` for a while now (from the start of the challenge it's been about an hour).. I will let it go a bit longer, but overall we probably can't afford running a job much longer than 1h during our nightlies because of the time constrains.

How long do you expect `wait-for-ml-lookback ` should take? The old version of the `append-ml` challenge takes ~40min. Not sure if you want to try to modify itso that there is somework done but still takes not much longer than 1h. We could also keep this version under a different name but not enabled it under nightlies if you think it's useful for investigations..

```rally  --target-host="192.168.14.13:39200" --track-path=~/rally-track/rally-tracks/nyc_taxis   --challenge="append-ml" --car="4gheap,trial-license,x-pack-ml" --client-options="timeout:240" --user-tag="benchmark:ml,user:ebadyano" --runtime-jdk="bundled" --pipeline="from-sources-complete"
Auto-updating Rally from origin
WARNING: You are using pip version 20.0.2; however, version 20.1 is available.
You should consider upgrading via the '/var/lib/jenkins/.pyenv/versions/3.8.0/bin/python3 -m pip install --upgrade pip' command.

    ____        ____
   / __ \____ _/ / /_  __
  / /_/ / __ `/ / / / / /
 / _, _/ /_/ / / / /_/ /
/_/ |_|\__,_/_/_/\__, /
                /____/

[INFO] Preparing for race ...
[INFO] Racing on track [nyc_taxis], challenge [append-ml] and car ['4gheap', 'trial-license', 'x-pack-ml'] with version [8.0.0-SNAPSHOT].

Running delete-index                                                           [100% done]
Running create-index                                                           [100% done]
Running delete-ml-datafeed                                                     [100% done]
Running delete-ml-job                                                          [100% done]
Running create-ml-job                                                          [100% done]
Running open-ml-job                                                            [100% done]
Running create-ml-datafeed                                                     [100% done]
Running check-cluster-health                                                   [100% done]
Running index                                                                  [100% done]
Running refresh-after-index                                                    [100% done]
Running force-merge                                                            [100% done]
Running refresh-after-force-merge                                              [100% done]
Running wait-until-merges-finish                                               [100% done]
Running start-ml-datafeed                                                      [100% done]
Running wait-for-ml-lookback                                                   [  0% done]
...
```

**Comment by benwtrent** [comment]
> How long do you expect wait-for-ml-lookback should take? The old version of the append-ml challenge takes ~40min.

That job was too simple. The average time to calculate the statistics for each bucket was not measurable. 

An option might be to not run this challenge against the entire corpus. Is that a valid option?

**Comment by ebadyano** [comment]
I ran with 30% of corpus on low mem env:
```
rally  --target-host="192.168.14.13:39200" --track-path=~/rally-track/rally-tracks/nyc_taxis   --challenge="append-ml" --car="4gheap,trial-license,x-pack-ml" --client-options="timeout:240" --user-tag="benchmark:ml,user:ebadyano" --runtime-jdk="bundled" --pipeline="from-sources-complete" --track-param="{\"ingest_percentage\":30}"
Auto-updating Rally from origin
WARNING: You are using pip version 20.0.2; however, version 20.1 is available.
You should consider upgrading via the '/var/lib/jenkins/.pyenv/versions/3.8.0/bin/python3 -m pip install --upgrade pip' command.

    ____        ____
   / __ \____ _/ / /_  __
  / /_/ / __ `/ / / / / /
 / _, _/ /_/ / / / /_/ /
/_/ |_|\__,_/_/_/\__, /
                /____/

[INFO] Preparing for race ...
[INFO] Racing on track [nyc_taxis], challenge [append-ml] and car ['4gheap', 'trial-license', 'x-pack-ml'] with version [8.0.0-SNAPSHOT].

Running delete-index                                                           [100% done]
Running create-index                                                           [100% done]
Running delete-ml-datafeed                                                     [100% done]
Running delete-ml-job                                                          [100% done]
Running create-ml-job                                                          [100% done]
Running open-ml-job                                                            [100% done]
Running create-ml-datafeed                                                     [100% done]
Running check-cluster-health                                                   [100% done]
Running index                                                                  [100% done]
Running refresh-after-index                                                    [100% done]
Running force-merge                                                            [100% done]
Running refresh-after-force-merge                                              [100% done]
Running wait-until-merges-finish                                               [100% done]
Running start-ml-datafeed                                                      [100% done]
Running wait-for-ml-lookback                                                   [100% done]
Running close-ml-job                                                           [100% done]

------------------------------------------------------
    _______             __   _____
   / ____(_)___  ____ _/ /  / ___/_________  ________
  / /_  / / __ \/ __ `/ /   \__ \/ ___/ __ \/ ___/ _ \
 / __/ / / / / / /_/ / /   ___/ / /__/ /_/ / /  /  __/
/_/   /_/_/ /_/\__,_/_/   /____/\___/\____/_/   \___/
------------------------------------------------------

|                                                         Metric |             Task |       Value |   Unit |
|---------------------------------------------------------------:|-----------------:|------------:|-------:|
|                     Cumulative indexing time of primary shards |                  |      58.443 |    min |
|             Min cumulative indexing time across primary shards |                  | 0.000266667 |    min |
|          Median cumulative indexing time across primary shards |                  |     29.2215 |    min |
|             Max cumulative indexing time across primary shards |                  |     58.4427 |    min |
|            Cumulative indexing throttle time of primary shards |                  |           0 |    min |
|    Min cumulative indexing throttle time across primary shards |                  |           0 |    min |
| Median cumulative indexing throttle time across primary shards |                  |           0 |    min |
|    Max cumulative indexing throttle time across primary shards |                  |           0 |    min |
|                        Cumulative merge time of primary shards |                  |     14.1808 |    min |
|                       Cumulative merge count of primary shards |                  |          29 |        |
|                Min cumulative merge time across primary shards |                  |           0 |    min |
|             Median cumulative merge time across primary shards |                  |     7.09041 |    min |
|                Max cumulative merge time across primary shards |                  |     14.1808 |    min |
|               Cumulative merge throttle time of primary shards |                  |     4.49647 |    min |
|       Min cumulative merge throttle time across primary shards |                  |           0 |    min |
|    Median cumulative merge throttle time across primary shards |                  |     2.24823 |    min |
|       Max cumulative merge throttle time across primary shards |                  |     4.49647 |    min |
|                      Cumulative refresh time of primary shards |                  |     1.16775 |    min |
|                     Cumulative refresh count of primary shards |                  |          43 |        |
|              Min cumulative refresh time across primary shards |                  |     0.00115 |    min |
|           Median cumulative refresh time across primary shards |                  |    0.583875 |    min |
|              Max cumulative refresh time across primary shards |                  |      1.1666 |    min |
|                        Cumulative flush time of primary shards |                  |    0.650967 |    min |
|                       Cumulative flush count of primary shards |                  |           9 |        |
|                Min cumulative flush time across primary shards |                  | 0.000333333 |    min |
|             Median cumulative flush time across primary shards |                  |    0.325483 |    min |
|                Max cumulative flush time across primary shards |                  |    0.650633 |    min |
|                                         Min ML processing time | benchmark_ml_job |           0 |     ms |
|                                        Mean ML processing time | benchmark_ml_job |     17.7653 |     ms |
|                                      Median ML processing time | benchmark_ml_job |          16 |     ms |
|                                         Max ML processing time | benchmark_ml_job |         472 |     ms |
|                                             Total Young Gen GC |                  |      46.127 |      s |
|                                               Total Old Gen GC |                  |           0 |      s |
|                                                     Store size |                  |     7.46818 |     GB |
|                                                  Translog size |                  | 6.00424e-06 |     GB |
|                                         Heap used for segments |                  |    0.117611 |     MB |
|                                       Heap used for doc values |                  |   0.0297737 |     MB |
|                                            Heap used for terms |                  |   0.0446777 |     MB |
|                                            Heap used for norms |                  | 0.000244141 |     MB |
|                                           Heap used for points |                  |           0 |     MB |
|                                    Heap used for stored fields |                  |   0.0429153 |     MB |
|                                                  Segment count |                  |          27 |        |
|                                                 Min Throughput |            index |     92764.8 | docs/s |
|                                              Median Throughput |            index |       95916 | docs/s |
|                                                 Max Throughput |            index |     97341.7 | docs/s |
|                                        50th percentile latency |            index |      729.36 |     ms |
|                                        90th percentile latency |            index |      1004.3 |     ms |
|                                        99th percentile latency |            index |     4199.31 |     ms |
|                                      99.9th percentile latency |            index |     5526.83 |     ms |
|                                       100th percentile latency |            index |     5887.18 |     ms |
|                                   50th percentile service time |            index |     729.395 |     ms |
|                                   90th percentile service time |            index |     1004.76 |     ms |
|                                   99th percentile service time |            index |     4199.31 |     ms |
|                                 99.9th percentile service time |            index |     5526.83 |     ms |
|                                  100th percentile service time |            index |     5887.18 |     ms |
|                                50th percentile processing time |            index |     734.918 |     ms |
|                                90th percentile processing time |            index |     1010.23 |     ms |
|                                99th percentile processing time |            index |     4205.92 |     ms |
|                              99.9th percentile processing time |            index |     5530.84 |     ms |
|                               100th percentile processing time |            index |     5892.31 |     ms |
|                                                     error rate |            index |           0 |      % |


----------------------------------
[INFO] SUCCESS (took 3567 seconds)
```
Takes about 1 hour. @benwtrent It's okay to merge this PR and I already merged a PR to run to run this  challenge with 30% of corpus during our nightlies.

Thank you!

**Comment by benwtrent** [comment]
@ebadyano THANKS!!!

**Comment by dliappis** [comment]
@ebadyano Could you please take a look at the necessary backports? I did a quick check and we have this challenge at least in branch `7`.

**Pull request merged**
